services:

  chat-room:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../.:/app/.
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    container_name: chat-room-db-container
    restart: always
    env_file: 
      - ../.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "chat-room-db"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

networks:
  default:
    name: chat-room_default